[[extensions]]
id = "cjpalhdlnbpafiamejdnhcphjbkeiagm"
name = "uBlock Origin"
source = "chrome-store"

[[extensions]]
id = "oboonakemofpalcgghocfoadofidjkkk"
name = "KeePassXC-Browser"
source = "chrome-store"

[[extensions]]
id = "mnjggcdmjocbbbhaepdhchncahnbgone"
name = "SponsorBlock for YouTube"
source = "chrome-store"

[[extensions]]
id = "hlepfoohegkhhmjieoechaddaejaokhf"
name = "Refined GitHub"
source = "chrome-store"

[[extensions]]
id = "kpaaapnegfaaoimjpagopchdbmenfngl"
name = "TWP - Translate Web Pages"
source = "url"
url = "https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v10.1.1.0/TWP_10.1.1.0_Chromium.crx"
